#!/bin/bash

REQUIRED_DEV_PACKAGES=(
    autoconf
    automake
    cmake
    curl
    dbus-devel
    eglexternalplatform-devel
    extra-cmake-modules
    file
    gcc
    gcc-c++
    gettext
    git
    glew-devel
    gstreamer1-devel
    gstreamermm-devel
    gtk3-devel
    libcurl-devel
    libmspack-devel
    libquadmath-devel
    libsecret-devel
    libspnav-devel
    libtool
    m4
    mesa-libGLU-devel
    ninja-build
    openssl-devel
    perl-FindBin
    systemd-devel
    texinfo
    wayland-protocols-devel
    wget
)

WEBKIT_CANDIDATES=("webkit2gtk4.1-devel" "webkit2gtk4.0-devel")
for candidate in "${WEBKIT_CANDIDATES[@]}"; do
    if dnf list --installed "${candidate}" >/dev/null 2>&1 || dnf list --available "${candidate}" >/dev/null 2>&1; then
        WEBKIT_PACKAGE="${candidate}"
        break
    fi
done

if [[ -z "${WEBKIT_PACKAGE}" ]]; then
    echo "Unable to determine a suitable webkit2gtk development package. Please install webkit2gtk4.1-devel (or webkit2gtk4.0-devel) manually."
else
    REQUIRED_DEV_PACKAGES+=("${WEBKIT_PACKAGE}")
fi

if [[ -n "$UPDATE_LIB" ]]
then
    NEEDED_PKGS=()
    for PKG in "${REQUIRED_DEV_PACKAGES[@]}"; do
        rpm -q "${PKG}" > /dev/null || NEEDED_PKGS+=("${PKG}")
    done

    if [[ "${#NEEDED_PKGS[*]}" -gt 0 ]]; then
        sudo dnf install -y "${NEEDED_PKGS[@]}"
    fi
    echo -e "done\n"
    exit 0
fi

export FOUND_GTK3_DEV
FOUND_GTK3_DEV=$(rpm -qa | grep -P '^gtk3-devel' || true)
